cluster: "sbatch -J {rule}.{wildcards} -p {resources.partition} -t {resources.runtime} -c {threads} --mem={resources.mem_mb}M -o logs/%x-%j.out -e logs/%x-%j.err"
jobs: 10
rerun-incomplete: true
latency-wait: 120
use-conda: true
printshellcmds: true
