executor: "cluster-generic"
cluster-generic-submit-cmd: "sbatch -J {rule}.{wildcards} -t {resources.runtime} -c {threads} --mem={resources.mem_mb}M -o logs/%x-%j.out -e logs/%x-%j.err"

jobs: 10
latency-wait: 120
rerun-incomplete: true
use-conda: true
printshellcmds: true
