executor: slurm
jobs: 10
resources:
    account=o_mykhaili,
    reservation=HumanGenetik
latency-wait: 120
rerun-incomplete: true
use-conda: true
printshellcmds: true
jobname: "{rule}.{wildcards}.{jobid}"
