reference: '/home/gpfs/o_mykhaili/galushka/reference/GCF_000001405.15_GRCh38_genomic.fna.gz'
data_dir: '/home/isilon/HumGenTempData/Matvii/data'
tmp_dir: '/home/isilon/HumGenTempData/Matvii/tmp'
results_dir: '/home/isilon/HumGenTempData/Matvii/results'