import pandas as pd

configfile: "config.yaml"
include: "rules/call_variants.smk"


df = pd.read_csv("../doc/sample_manifest.csv")
SAMPLES = df.set_index("sample_id")["bam_path"].to_dict()

rule all:
    input:
        expand("../tmp/{sample}.vcf.gz", sample=SAMPLES.keys())
