reference: '/home/gpfs/o_mykhaili/galushka/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna'
data_dir: '/home/isilon/HumGenTempData/Matvii/data'
tmp_dir: '/home/isilon/HumGenTempData/Matvii/tmp'
results_dir: '/home/isilon/HumGenTempData/Matvii/results'