reference: '/home/gpfs/o_mykhaili/galushka/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna'
reference_local: '/mnt/data/reference_genome/NCBI_GCA_1405.15_GRCH38_no_alts_with_decoys/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna'
vc_data_dir: '/home/isilon/HumGenTempData/Matvii/data/vc'
tmp_dir: '/home/isilon/HumGenTempData/Matvii/tmp'
results_dir: '/home/isilon/HumGenTempData/Matvii/results'
testing: False